version: '3.3'
services:  
    unfetter-ui:
      build: ./
      image: unfetter-ui
      container_name: unfetter-ui-build
      volumes:
      - ./src:/usr/share/unfetter-ui/src
      entrypoint:
      - npm
      - run
      # - build:prod:noclean:ff31
      - build:demo:noclean:ff31
      # - build:prod:noclean
      # - build:demo:noclean
      volumes:
      - ./dist:/usr/share/unfetter-ui/dist
