export enum StixUrls {
    ATTACK_PATTERN = 'api/attack-patterns',
    CAMPAIGN = 'api/campaigns',
    COURSE_OF_ACTION = 'api/course-of-actions',
    IDENTITY = 'api/identities',
    INDICATOR = 'api/indicators',
    MALWARE = 'api/malwares',
    MARKING_DEFINITION = 'api/marking-definitions',
    OBSERVED_DATA = 'api/observed-data',
    RELATIONSHIP = 'api/relationships',
    REPORT = 'api/reports',
    SIGHTING = 'api/sightings',
    THREAT_ACTOR = 'api/threat-actors',
    TOOL = 'api/tools',
    X_UNFETTER_THREAT_BOARD = 'api/x-unfetter-threat-boards',
}
